### ISSUE TITLE
option to ignore permissions for alwaysbeheadmob and alwaysbehead

### ISSUE THREAD

**Issue by AlbinReidar** [crashdemons/PlayerHeads#25]
Me and the ops on my server have all perms because it makes things easier but there is no way to turn this off with it being part of the perms instead of the config. Can you please add this so people with all perms don't just behead everything? We are currently using minecraft version 1.14.4.

**Comment by crashdemons** [comment]
Have you tried denying (or "negating") the permissions (playerheads.alwaysbehead, etc) for a group all of your staff are in?  you should be able to do this with your permissions plugin or with permissions.yml

With permissions.yml, I believe you can add a permission with a dash in front (without a space, as part of the name) to negate the permission.
If you use something like LuckPerms, it should be as easy as setting the permission to 'deny' rather than allow.

This, means you will need to add a group to your existing ops though.

**Comment by AlbinReidar** [comment]
Thanks i did not know that was a thing and it fixed my issue i love the plugin man keep up the great work!

**Comment by AlbinReidar** [comment]
I had to undo that change as it worked at first but after another server restart later that comand in PermissionsEX broke the PermissionsEX plugin and stopped most of my server from working

**Comment by crashdemons** [comment]
what command(s) did you use?

**Comment by AlbinReidar** [comment]
normal perms would be - playerheads.alwaysbeheadmob but i did -playerheads.alwaysbeheadmob to try and negate it. as well as -playerheads.alwaysbehead ill try the way you have posted in your comment for negatedperms

**Comment by AlbinReidar** [comment]
it does not negate it that way so i dont think negating it works with PermissionsEX. because the first way i negated it was just -playerheads.alwaysbehead and that worked for a bit but then broke permissionsEX so is there anyway you can add it to the config instead to be turned on and off?

**Comment by crashdemons** [comment]
if it breaks PEX then something else is wrong with your PEX configuration or how you're applying the permission because it's a documented feature of PEX and basically every other permissions plugin...  Being able to deny permissions is basic functionality that even bukkit supported without PEX.

Could you post your permissions configuration from after it breaks?

---

I mean, sure there could be an option to ignore permissions but it's not proper at all to do so, and it seems like a very specific request for a pretty isolated issue.

**Comment by AlbinReidar** [comment]
I had to change it to a .txt so you can read it but thats the .yml after it breaks currently i only have it applied to rank king
[permissions.txt](https://github.com/crashdemons/PlayerHeads/files/3604041/permissions.txt)

**Comment by AlbinReidar** [comment]
when it breaks because of that console spams this "12.09 06:39:05 [Server] Server thread/INFO Error: Permissions manager is not accessable. Is the PermissionsEx plugin enabled?"

**Comment by crashdemons** [comment]
did you use the updated version with the star permission on bottom?
You may also want to try negating `playerheads.*` (before star) since that will inherit alwaysbehead.
Then any permissions you want to explicitly allow must go before both wildcard permissions.
eg:
```
  King:
    build: true
    permissions:
    - playerheads.spawn
    - -playerheads.alwaysbehead
    - -playerheads.alwaysbeheadmob
    - -playerheads.*
    - '*'
```
Again I'm not expert in PEX (and they have their own support options) but your issue is exacerbated by using the star permission (grant all) rather than being more specific, which is going to make life difficult for a lot of plugins.

**Comment by crashdemons** [comment]
Another thing to check is whether you're using this setting in PEX:

![image](https://user-images.githubusercontent.com/3233238/64858216-4b274480-d616-11e9-8d35-930db018b621.png)

since this overrides any permissions you set.

**Comment by AlbinReidar** [comment]
> did you use the updated version with the star permission on bottom?
> You may also want to try negating `playerheads.*` (before star) since that will inherit alwaysbehead.
> Then any permissions you want to explicitly allow must go before both wildcard permissions.
> eg:
> 
> ```
>   King:
>     build: true
>     permissions:
>     - playerheads.spawn
>     - -playerheads.alwaysbehead
>     - -playerheads.alwaysbeheadmob
>     - -playerheads.*
>     - '*'
> ```
> 
> Again I'm not expert in PEX (and they have their own support options) but your issue is exacerbated by using the star permission (grant all) rather than being more specific, which is going to make life difficult for a lot of plugins.

i set it up just like this and now its working properly for my ops that have all perms thanks so much i never knew how to properly negate commands before with pex. the issue was with having the - '*' above the other commands so anything i was to negate i always have to add above it. the command - '*' is just a simple way of granting ops all permissions rather than typing them out for ranks so this really does help a bunch!
