### ISSUE TITLE
Different villager profession - different head

### ISSUE THREAD

**Issue by SirvydasS** [crashdemons/PlayerHeads#48]
Add more villager's drop heads. What profession the villagers killed the head of that profession and you get.

Example:
![unknown](https://user-images.githubusercontent.com/8950371/98435995-393d1680-20e0-11eb-8c3b-f9ae8a31ae67.png)

**Comment by crashdemons** [comment]
This has been requested before, but PlayerHeads is currently committed to providing a single head for each distinct mob [entity type](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html#enum.constant.summary).

The reason for this is firstly to keep the plugin small and easy to maintain, update, and backport to other versions.

The other reason is because once you start deciding to add heads for variants of each mob, the number of required heads goes up exponentially. (consider someone else asking for baby versions of all of those, and all other mobs, consider a head for all 3,584 tropical fish, etc...)

Adding additional variant support at this point will further complicate backported features (eg: Husk detection on certain server versions is already a problem).

Now, there are a couple options if you still want this feature.
[DropHeads](https://dev.bukkit.org/projects/dropheads) is a plugin that is already aimed at eventually adding heads for every variant and this might better suit you.
Alternatively, there is a [PlayerHeads API](https://dev.bukkit.org/projects/player-heads/pages/api-documentation) and you are able to use the head-drop events to substitute your own custom heads with your own plugin, and even use newer API profile features to help create a custom head for that.
Anyone is also free to fork the project and add their own support.

But, regardless, of the choice the this PlayerHeads repo will not be entertaining mob variant heads at this time for maintenance reasons.

I am sorry for any inconvenience this causes.
